# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app files
COPY . .

# Expose port
EXPOSE 3333
#  print path and content
RUN pwd && ls -la

RUN npm run build

# Start middleware
CMD ["npm", "start"]
